version: '3.8'

services:
    webapp:
        image: app
        environment:
            NODE_ENV: production
        build:
            context: .
            dockerfile: './Dockerfile'
        ports:
            - '8080:80'
            